accounts:
  - name: alice
    coins: ["1000koala"]
  - name: bob
    coins: ["1000koala"]
validator:
  name: alice
  staked: "1000koala"
client:
  vuex:
    path: "vue/src/store"
faucet:
  name: bob 
  coins: ["2koala"]
